### PR TITLE
Fix nested transitions

### PR DESCRIPTION
**Pull request by Razboy20**
`Transition` will now wait for all `ChildTransition` components underneath to finish transitioning before removing itself. This also fixes early `transitionEnd` calls by cancelling transition/animation event bubbling. (e.g. if you have a button that you hover over which causes a transition event, this would be accidentally listened to.)

### CODE REVIEW

**Comment by Razboy20** [comment]
Should also fix #15.

**Comment by lxsmnsyc** [comment]
Thanks for making this PR! I would like to suggest one thing though: add comments. I know that I don't add it myself (to which I'll do in the foreseeable future) but the reason I would want comments is because I would like to know how this works myself too 🤣

**Comment by Razboy20** [comment]
Added a couple comments/renamed some variables to hopefully improve the code readability.

Another transition example also sounds like a good idea-maybe might be good to create some more pages to the solid-headless website as well, or be able to view all the examples on there.

**Comment by lxsmnsyc** [comment]
solid-headless site itself is collecting dusts. I'll be recreating it from scratch again since I found an SSR setup I liked

**Pull request merged**
