### PR TITLE
utilize dynamic dependencies

### PR DESCRIPTION
**Pull request by thetarnav**
Why not utilize dynamic dependencies here?

### CODE REVIEW

**Comment by lxsmnsyc** [comment]
The old code is that way however due to boolean short-circuit the latter code doesn't get tracked. That's the reason why I had to expand it into variable reads. Thanks for the PR but closing this.

**Comment by thetarnav** [comment]
Yeah, I know that it doesn't get tracked. That's the point 😉
Why track a signal which updates won't case a change? The first signal has to return false for the second to even matter.
But yeah, it's not that important, just found that curious while looking through the code 😛

**Comment by lxsmnsyc** [comment]
Revisiting the concept, you might be right. I'll re-open this for now since the changed code is just one of the many same occurrences that I have changed in my local branch.

**Comment by lxsmnsyc** [comment]
Had to close this now due to a massive rewrite, but thanks for contributing!

**Pull request closed without merging**
